### ISSUE TITLE
placeholder with prefix

### ISSUE THREAD

**Issue by dudo** [nosir/cleave.js#133]
https://jsfiddle.net/nosir/gLLsrxxf/

If we have a prefix, the placeholder seems to be getting lost. Any work around for this?

**Comment by nosir** [comment]
Well good one.
I guess no work around by using this lib.
The only way I can think of is to have prefix as a layer on top of the input field, and set a padding for the input content :p
Sorry, will close this.

**Comment by turgayozgur** [comment]
Just use like this:
`new Cleave($('.input-phone'), {
       delimiters: ['+90 (', ')', ' ', '-'],
       blocks: [0, 3, 0, 3, 4],
       numericOnly: true
   });`

**Comment by Jucesr** [comment]
I was able to get it done by styling just like @nosir said. Kinda ugly though

Here is the example


```js

<CustomInput
          field='cost'
          placeholder="Cost"
          prefix="$"
          options={{
            // prefix: '$',
            numeral: true,
            numeralThousandsGroupStyle: 'thousand',
            rawValueTrimPrefix: true
          }}
/>

const CustomInput = ({props}) => {
  return (
    <div className="CustomInput">
      <span className="CustomInput_prefix">{prefix}</span>
      <Cleave
        {...props}
        className="CustomInput_input"
      />
    </div>
  )
}
```
```css
.CustomInput{
  border: 1px solid rgb(194, 194, 194);
  margin-bottom: 10px;
}

.CustomInput_prefix{
  padding-left: 10px;
  color: gray;
}

.CustomInput_input{
  border: none;
  padding: 10px 10px 10px 0;
  color: gray;
  outline: none;
}

.CustomInput_input::placeholder { 
    color: gray;
    opacity: 1; 
}
```
![image](https://user-images.githubusercontent.com/25498381/43447487-79cfb658-9460-11e8-95e1-e8251fab0438.png)

![image](https://user-images.githubusercontent.com/25498381/43447521-87c1afb4-9460-11e8-97e3-bf7a2dc2f548.png)
